[custom.all.ampii]
type = "local"
path = "."
ipkg = "ampii.ipkg"

[custom.all.date]
type   = "github"
url    = "https://github.com/emdash/idris-datetime"
commit = "fetch-latest:main"
ipkg   = "date.ipkg"

[custom.all.tui]
type   = "github"
url    = "https://github.com/emdash/idris2-tui"
commit = "fetch-latest:main"
ipkg   = "tui.ipkg"

[custom.all.tui-async]
type   = "github"
url    = "https://github.com/emdash/idris2-tui"
commit = "fetch-latest:main"
ipkg   = "tui-async/tui-async.ipkg"
